[scrapyd]
http_port         = 6801
bind_address      = 127.0.0.1
logs_dir          = /var/lib/scrapyd/logs
items_dir         = /var/lib/scrapyd/items
dbs_dir           = /var/lib/scrapyd/dbs
eggs_dir          = /src/eggs
